/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ims;

import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class issuetext extends javax.swing.JFrame {

    /**
     * Creates new form issuetext
     */
    public issuetext() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ISSUE = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ISSUETA = new javax.swing.JTextArea();
        ID = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        NAME = new javax.swing.JLabel();
        NAMET = new javax.swing.JTextField();
        IDT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        REGARDC = new javax.swing.JComboBox<>();
        REGARD = new javax.swing.JLabel();
        BRANCHC = new javax.swing.JComboBox<>();
        BRANCH = new javax.swing.JLabel();
        REPORT = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setForeground(new java.awt.Color(254, 238, 238));

        ISSUE.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        ISSUE.setForeground(new java.awt.Color(127, 207, 221));
        ISSUE.setText("ISSUE");

        ISSUETA.setColumns(20);
        ISSUETA.setRows(5);
        ISSUETA.setText("write your issues        ");
        ISSUETA.setWrapStyleWord(true);
        ISSUETA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(24, 201, 174)));
        jScrollPane1.setViewportView(ISSUETA);

        ID.setBackground(new java.awt.Color(32, 29, 26));
        ID.setFont(new java.awt.Font("TlwgTypewriter", 1, 20)); // NOI18N
        ID.setForeground(new java.awt.Color(1, 209, 190));
        ID.setText("ID");

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        NAME.setBackground(new java.awt.Color(7, 7, 7));
        NAME.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        NAME.setForeground(new java.awt.Color(0, 202, 238));
        NAME.setText("NAME");

        NAMET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMETActionPerformed(evt);
            }
        });

        IDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(24, 13, 1));
        jLabel4.setFont(new java.awt.Font("DejaVu Serif", 0, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 226, 230));
        jLabel4.setText("FORM\n");

        REGARDC.setBackground(new java.awt.Color(18, 9, 0));
        REGARDC.setForeground(new java.awt.Color(108, 233, 254));
        REGARDC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CERTIFICATES", "BANK", "DIRECTOR", "HEALTH", "OUTPASS", "HOSTEL ISSUES", "ACADEMICS", "DEPARTMENT", "BRANCH", "MISCENELLNOUS", " ", " ", " ", " ", " " }));
        REGARDC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 211, 254)));
        REGARDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGARDCActionPerformed(evt);
            }
        });

        REGARD.setBackground(new java.awt.Color(13, 12, 12));
        REGARD.setFont(new java.awt.Font("Umpush", 1, 20)); // NOI18N
        REGARD.setForeground(new java.awt.Color(1, 254, 234));
        REGARD.setText("REGARDING");

        BRANCHC.setBackground(new java.awt.Color(6, 6, 6));
        BRANCHC.setForeground(new java.awt.Color(26, 253, 212));
        BRANCHC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PUC 1", "PUC 2", "CSE", "MECH", "ME", "CHEM", "ECE", "CIVIL" }));
        BRANCHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRANCHCActionPerformed(evt);
            }
        });

        BRANCH.setBackground(new java.awt.Color(1, 1, 1));
        BRANCH.setFont(new java.awt.Font("Ubuntu Light", 1, 20)); // NOI18N
        BRANCH.setForeground(new java.awt.Color(0, 255, 255));
        BRANCH.setText("BRANCH");

        REPORT.setBackground(new java.awt.Color(1, 1, 1));
        REPORT.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        REPORT.setForeground(new java.awt.Color(0, 240, 255));
        REPORT.setText("REPORT");
        REPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BRANCH)
                            .addComponent(ISSUE, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IDT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BRANCHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(REGARD)
                                .addGap(35, 35, 35)
                                .addComponent(REGARDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NAME)
                                .addGap(44, 44, 44)
                                .addComponent(NAMET, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jButton2)
                .addGap(64, 64, 64)
                .addComponent(REPORT)
                .addGap(108, 108, 108)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID)
                            .addComponent(IDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NAMET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NAME))
                        .addGap(7, 7, 7)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REGARDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGARD)
                    .addComponent(BRANCHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BRANCH))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ISSUE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REPORT)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling cDFJ KJDSHFJDKJF
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BRANCHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRANCHCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BRANCHCActionPerformed

    private void REPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTActionPerformed
        // TODO add your handling code here
        String a=IDT.getText();
         String b=NAMET.getText();
         String c;
        c = (String) BRANCHC.getSelectedItem();
        String d=(String) REGARDC.getSelectedItem();
        String e=(String)ISSUETA.getText();
       
       
       try{
          Connect cc;
            cc = new Connect();
            String q=   "insert into report values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"')";
                cc.s.executeUpdate(q);
                JOptionPane.showMessageDialog(null,"REPORT SENT");
                
               
               
          
       }catch(Exception ee){
                System.out.println("The error is:"+ee);}
                                
                                
        
    }//GEN-LAST:event_REPORTActionPerformed

    private void IDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTActionPerformed

    private void REGARDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGARDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGARDCActionPerformed

    private void NAMETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMETActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         JFRAME_JTABLE.AddRowToJTable(new Object[]{IDT.getText(),
                                                  NAMET.getText(),
                                                  NAMET.getText(),
                                                  });
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issuetext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issuetext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issuetext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issuetext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issuetext().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BRANCH;
    private javax.swing.JComboBox<String> BRANCHC;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDT;
    private javax.swing.JLabel ISSUE;
    private javax.swing.JTextArea ISSUETA;
    private javax.swing.JLabel NAME;
    private javax.swing.JTextField NAMET;
    private javax.swing.JLabel REGARD;
    private javax.swing.JComboBox<String> REGARDC;
    private javax.swing.JButton REPORT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
